
Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Condition: CreateMetricsStack
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"

  LambdaExecutionPolicy:
    DependsOn: LambdaExecutionRole
    Type: AWS::IAM::Policy
    Condition: CreateMetricsStack
    Properties:
      PolicyName: AccessToCloudwatchForBuildkiteMetrics
      Roles:
      - $(LambdaExecutionRole)
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          - cloudwatch:PutMetricData
          - autoscaling:SetInstanceHealth
          Resource:
          - "*"

  BuildkiteMetricsFunction:
    Type: AWS::Lambda::Function
    DependsOn:
    - LambdaExecutionRole
    - LambdaExecutionPolicy
    Condition: CreateMetricsStack
    Properties:
      Code:
        S3Bucket: $(MetricsLambdaBucket[$(AWS::Region)][Bucket])
        S3Key: "buildkite-metrics-v1.4.1-lambda.zip"
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Timeout: 60
      Handler: handler.handle
      Runtime: python2.7
      MemorySize: 128
      Environment:
        Variables:
          BUILDKITE_TOKEN: $(BuildkiteApiAccessToken)
          BUILDKITE_ORG: $(BuildkiteOrgSlug)
          BUILDKITE_QUEUE: $(BuildkiteQueue)

  ScheduledRule:
    Type: "AWS::Events::Rule"
    Condition: CreateMetricsStack
    Properties:
      Description: "ScheduledRule"
      ScheduleExpression: "rate(1 minute)"
      State: "ENABLED"
      Targets:
        - Arn:
            Fn::GetAtt:
              - "BuildkiteMetricsFunction"
              - "Arn"
          Id: "TargetBuildkiteMetricsFunction"

  PermissionForEventsToInvokeLambda:
    Type: "AWS::Lambda::Permission"
    Condition: CreateMetricsStack
    Properties:
      FunctionName: $(BuildkiteMetricsFunction)
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "ScheduledRule"
          - "Arn"
